services:
  - type: web
    name: edu-agent-system-api
    runtime: python
    rootDir: edu_mvp/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_clean:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.12
    plan: free
